name: Auto-Merge-PRs

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]
    
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: emiliopedrollo/auto-merge@v1.2.0
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          target_branch: ${{ github.sha }}
          
